### ISSUE TITLE
Edit features (client)

### ISSUE THREAD

**Issue by marcel-dancak** [gisquick/gisquick#80]
**Tasks:**

- [x] Extend info panel for feature editor (slot for new toolbar, toggle edit button)

- [x] Create FeatureEditor component

- [x] Create generic edit form for attributes

- [x] Create geometry editor

- [x] Save changes through server API

Integration of OpenLayers into Vue.js is not very straightforward. Geometry editor will require use of several OL objects connected to user interface (component's state in Vue). So it will be important to find good practices for cooperation between these 'view' libraries.

**Known pitfalls:**
* Plain storing of OL objects in Vue component's data will automatically convert them to reactive objects, which is not good. OL objects are complex structures with many references to other objects.
* Vue components are more declarative and data driven. In normal cases you should control component by changing prop's values. On the other side, OL use more imperative approach, objects have constructor and many properties cannot be changed after object's creation, and also in most cases you use methods to change object's state (or communication with other objects).
